name: First Workflow

on:
  push:
    branches:
      - main

jobs:
   example-job:
     runs-on: ubuntu-latest

     steps:
      - name: Print a welcome message
        run: echo "welcome to our first Github Action workflow!"

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: List repository file
        run:  ls -la
