on :
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "staging"
        options:
          - staging
          - production

jobs:
  deploy: 
    runs-on: ubunto-latest
    steps:
      - name: Deploy application
        run: echo "Deploying the application...."
        
